merge setup_contestant_env.sh into oisetup

diff --git a/vm-contestant/usr/local/sbin/oisetup b/vm-contestant/usr/local/sbin/oisetup
--- a/vm-contestant/usr/local/sbin/oisetup
+++ b/vm-contestant/usr/local/sbin/oisetup
@@ -66,37 +66,14 @@ function get_domain {
 
 }
 
-function update_from_repo {
+function install_from_repo {
 
-        if test -z "$param_skiprespawn"; then # $param_skiprespawn will be true when the script has been called by itself after updating the repo
-                if test ! -d "$REPO_PATH"; then
-                        echo "Installing from repo..."
-                        git clone "$REPO_URL" "$REPO_PATH" && repo_updated="true"
-                elif test "$(git -C "$REPO_PATH" ls-remote "$REPO_URL" refs/heads/main | cut -f1)" != "$(git -C "$REPO_PATH" rev-parse refs/heads/main)"; then
-                        echo "Updating from repo..."
-                        git -C "$REPO_PATH" pull && repo_updated="true"
-                fi
-                if test -n "$repo_updated"; then
-                        echo "Respawning with updated code..."
-                        exec -- "$0" "$@" --skip-respawn # Rerun this script in case it has been updated in repo
-                        exit 0
-                fi
-        else
-                echo "Respawning completed"
-        fi
-
-        if test -d "$REPO_PATH/vm-proctor"; then
-                echo "Deleting proctor server repo files..."
-                rm -rf "$REPO_PATH/vm-proctor"
-        fi
+        echo "Installing proctoring system."
+        "$REPO_PATH/vm-contestant/install.sh" -s || exit 1
 
 }
 
-function install_proctor {
-
-        echo "Installing proctoring system..."
-
-        "$REPO_PATH/vm-contestant/install.sh"
+function install_requirements {
 
         sudo apt install -y moreutils idn ipset pypy3 python3-pip python-is-python3 xosd-bin xdotool lz4json jq sqlite3 git
         sudo pip3 install --break-system-packages python-pytun queuelib requests
@@ -106,7 +83,175 @@ function install_proctor {
 function configure_contestant_env {
 
         echo "Configuring contest environment..."
-        "$REPO_PATH/vm-contestant/setup_contestant_env.sh" "$TIMEZONE" "$PROCTOR_USERNAME" "$CUSTOM_LINE_COMMENT"
+
+        # Update the system
+        apt update -y
+        apt upgrade -y
+
+        # Timezone
+        test -n "$TIMEZONE" && timedatectl set-timezone "$TIMEZONE"
+
+        # Keep log small
+        remove_custom_lines /etc/systemd/journald.conf
+        echo "SystemMaxUse=100M # $CUSTOM_LINE_COMMENT" >> /etc/systemd/journald.conf
+        systemctl restart systemd-journald
+
+        # Disable os update norifications
+        remove_custom_lines /etc/update-manager/release-upgrades
+        echo "Prompt=never # $CUSTOM_LINE_COMMENT" >> /etc/update-manager/release-upgrades
+        grep -q Hidden=true /etc/xdg/autostart/update-notifier.desktop 2>/dev/null || (touch /etc/xdg/autostart/update-notifier.desktop && echo "Hidden=true" >> /etc/xdg/autostart/update-notifier.desktop)
+
+        # Remove shutdown menu
+        mkdir -p /etc/guest-session/skel/.config/xfce4/xfconf/xfce-perchannel-xml/
+        cat > /etc/guest-session/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-session.xml << EOF
+<?xml version="1.0" encoding="UTF-8"?>
+<channel name="xfce4-session" version="1.0">
+  <property name="shutdown" type="empty">
+    <property name="ShowSwitchUser" type="bool" value="false"/>
+    <property name="ShowHibernate" type="bool" value="false"/>
+    <property name="ShowSuspend" type="bool" value="false"/>
+    <property name="ShowHybridSleep" type="bool" value="false"/>
+  </property>
+</channel>
+EOF
+        mkdir -p /etc/xdg/xfce4/kiosk
+        cat > /etc/xdg/xfce4/kiosk/kioskrc << EOF
+        [xfce4-session]
+        SaveSession=NONE
+        EOF
+
+        # Create oi user
+        if ! id "$PROCTOR_USERNAME" >/dev/null 2>&1; then
+                oi_user_pwd="$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1)"
+                useradd -m "$PROCTOR_USERNAME" && echo "$PROCTOR_USERNAME:$oi_user_pwd" | chpasswd && echo "ATTENTION: Created new user oi with password: $oi_user_pwd"
+                oi_user_pwd="" # Clear password from memmory
+        fi
+
+        # Allow SSH connections into oi user
+        apt install -y ssh
+        remove_custom_lines /etc/ssh/ssh_config.d/oi.conf true
+        cat >> /etc/ssh/ssh_config.d/oi.conf << EOF
+PermitRootLogin no # $CUSTOM_LINE_COMMENT
+UseDNS no # $CUSTOM_LINE_COMMENT
+PasswordAuthentication no # $CUSTOM_LINE_COMMENT
+ChallengeResponseAuthentication no # $CUSTOM_LINE_COMMENT
+AllowUsers $PROCTOR_USERNAME # $CUSTOM_LINE_COMMENT
+EOF
+        systemctl restart sshd
+        test ! -d "/home/$PROCTOR_USERNAME/.ssh" && mkdir "/home/$PROCTOR_USERNAME/.ssh" && chown "$PROCTOR_USERNAME" "/home/$PROCTOR_USERNAME/.ssh"
+        ! test -f "/home/$PROCTOR_USERNAME/.ssh/authorized_keys" && touch "/home/$PROCTOR_USERNAME/.ssh/authorized_keys"
+        grep -qvE '^[[:space:]]*(ssh|ecdsa)-' "/home/$PROCTOR_USERNAME/.ssh/authorized_keys" && echo "Attention: Add in /home/$PROCTOR_USERNAME/.ssh the ssh-rsa generated by the proctor"
+        sudo chown oi:oi -R "/home/$PROCTOR_USERNAME/.ssh"
+        sudo chmod go-rwx -R "/home/$PROCTOR_USERNAME/.ssh"
+
+        # Guest user startup scripts
+        remove_custom_lines /etc/guest-session/prefs.sh true
+        echo "ln -sf $HOME /home/contestant # $CUSTOM_LINE_COMMENT" >> /etc/guest-session/prefs.sh
+        echo "adduser $USER guests # $CUSTOM_LINE_COMMENT" >> /etc/guest-session/prefs.sh
+
+        # Boot into guest user (all settings are lost at logoff)
+        echo "[Seat:*]\nallow-guest=true\nautologin-guest=true" > /etc/lightdm/lightdm.conf.d/40-enable-guest.conf
+        echo "[Seat:*]\ngreeter-setup-script=/usr/local/sbin/lock_message.sh" > /etc/lightdm/lightdm.conf.d/40-enable-lock-message.conf.disable
+
+        # Guest user init
+        test ! -d /etc/guest-session/skel/ && mkdir /etc/guest-session/skel/
+
+        # Enlarge processes stack and recursivity to equalize that of CMS evaluations
+        cat > /etc/security/limits.d/30-stack.conf << EOF
+hard stack 262144
+soft stack 262144
+EOF
+        remove_custom_lines /etc/guest-session/skel/.profile true
+        echo "ulimit -s 262144 # $CUSTOM_LINE_COMMENT" >> /etc/guest-session/skel/.profile
+
+        #s Install Firefox compatible with guest user. Ubuntu now ships firefox as a Snap, so we need to install it as a deb in order to prepopulate its configuration for the guest user
+        apt autopurge -y chromium-browser
+        snap remove chromium
+        snap remove firefox
+        apt autopurge -y snapd
+        add-apt-repository -y ppa:mozillateam/ppa
+        cat > /etc/apt/preferences.d/mozilla-firefox << EOF
+Package: *
+Pin: release o=LP-PPA-mozillateam
+Pin-Priority: 1001
+EOF
+        echo 'Unattended-Upgrade::Allowed-Origins:: "LP-PPA-mozillateam:${distro_codename}";' > /etc/apt/apt.conf.d/51unattended-upgrades-firefox
+        apt update
+        apt install -y firefox
+        /usr/bin/xdg-settings set default-web-browser firefox.desktop
+        # Disable AppArmor so firefox works correctly in guest session
+        sed -i 's/^GRUB_CMDLINE_LINUX=""/GRUB_CMDLINE_LINUX="apparmor=0"/' /etc/default/grub
+        update-grub
+
+        # Install (de)compression tool integrated with file namanger
+        apt install -y thunar-archive-plugin
+
+        # Install development tools
+        sudo apt install -y build-essential clang vim idle default-jdk g++ geany
+
+        # Default to C++17
+        rm -f /bin/g++ /usr/bin/g++
+        echo -r '#!/bin/bash\nexec /bin/g++-11 -std=c++17 "$@"' > /bin/g++
+        chmod a+rx /bin/g++
+        ln -f /bin/g++ /usr/bin/g++ 2>/dev/null # Not symbolic link, hard link
+
+        # Install Sublime text
+        apt install -y wget
+        wget -qO- https://download.sublimetext.com/sublimehq-pub.gpg > /etc/apt/keyrings/sublimehq-pub.asc
+        echo -e 'Types: deb\nURIs: https://download.sublimetext.com/\nSuites: apt/stable/\nSigned-By: /etc/apt/keyrings/sublimehq-pub.asc' > /etc/apt/sources.list.d/sublime-text.sources
+        apt update
+        apt install -y sublime-text
+
+        # Install VSCode
+        apt install -y gpg
+        wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor --batch --yes -o /usr/share/keyrings/microsoft.gpg
+        echo -e "Types: deb\nURIs: https://packages.microsoft.com/repos/code\nSuites: stable\nComponents: main\nArchitectures: amd64,arm64,armhf\nSigned-By: /usr/share/keyrings/microsoft.gpg" > /etc/apt/sources.list.d/vscode.sources
+        apt update
+        apt install -y code
+        mkdir -p /etc/guest-session/skel/.local/share/applications
+        cat > /etc/guest-session/skel/.local/share/applications/code.desktop << EOF
+[Desktop Entry]
+Name=Visual Studio Code
+Comment=Code Editing. Redefined.
+GenericName=Text Editor
+Exec=/usr/share/code/code --no-sandbox %F
+Icon=vscode
+Type=Application
+StartupNotify=false
+StartupWMClass=Code
+Categories=TextEditor;Development;IDE;
+MimeType=application/x-code-workspace;
+Actions=new-empty-window;
+Keywords=vscode;
+[Desktop Action new-empty-window]
+Name=New Empty Window
+Name[de]=Neues leeres Fenster
+Name[es]=Nueva ventana vacía
+Name[fr]=Nouvelle fenêtre vide
+Name[it]=Nuova finestra vuota
+Name[ja]=新しい空のウィンドウ
+Name[ko]=새 빈 창
+Name[ru]=Новое пустое окно
+Name[zh_CN]=新建空窗口
+Name[zh_TW]=開新空視窗
+Exec=/usr/share/code/code --no-sandbox --new-window %F
+Icon=vscode
+EOF
+        code --install-extension ms-vscode.cpptools
+        code --install-extension ms-python.python
+        code --install-extension ms-vscode.cpptools
+        cp -r ~/.vscode /etc/guest-session/skel/.vscode
+        rm -f /etc/guest-session/skel/.vscode/argv.json
+
+        # Remove unnecessary applications
+        apt autopurge -y libreoffice-* thunderbird transmission-* xfburn pidgin
+
+        # Disable keyrings prompts
+        apt autopurge -y gnome-keyring seahorse
+
+        # Clean up
+        sudo apt autoremove -y --purge
+        sudo apt clean -y
 
 }
 
@@ -620,15 +765,14 @@ dns_lockdown_implicit_exceptions=""
 param_profile=""
 param_defrag=""
 param_refresh=""
-param_gitpull=""
+param_install=""
 param_configos=""
 param_skipos=""
-param_skiprespawn=""
 param_help=""
 param_error=""
 
 # Context checks
-test "$EUID" -ne 0 && error "This script must be run as root!"
+test "$EUID" -ne 0 && echo "This script must run with root privileges. Requesting permission." && exec sudo "$0" "$@"
 
 # Commandline checks
 for param in $@; do
@@ -642,8 +786,8 @@ for param in $@; do
                 -d | --defragment)
                         param_defrag="true"
                         ;;
-                -g | --gitpull)
-                        param_gitpull="true"
+                -i | --install)
+                        param_install="true"
                         ;;
                 -c | --config-os)
                         param_configos="true"
@@ -651,8 +795,8 @@ for param in $@; do
                 -F | --skip-os-check)
                         param_skipos="true"
                         ;;
-                --skip-respawn)
-                        param_skiprespawn="true"
+                --skip-install)
+                        param_skipinstall="true"
                         ;;
                 -*)
                         param_error="true"
@@ -666,9 +810,12 @@ done
 
 if is_enabled "$param_help" || is_enabled "$param_error"; then
         is_enabled "$param_error" && echo "Invalid arguments!"
-        echo -e "Usage: $(basename "$0") [profile] [options]...\nAvailable profiles:\n\t$(for file in "$OISETUP_PROFILES_PATH"/*; do test -L "$file" || basename "$(echo "$file")"; done | sort | xargs)\nProfiles are located in:\n\t$OISETUP_PROFILES_PATH\nOptions:\n\t-d --defragment\tDefragment the disk (so it can later be compacted and compressed for distribution)\n\t-r --refresh\tOnly refresh the profile, keep persistent data\n\t-g --gitpull\tUpdate from git repo before installing\n\t-c --config-os\tSets up the contest environment\n-F --skip-os-checks\tDo not check if the OS matches\n\t-h --help\tDisplay this help message"
+        echo -e "Usage: $(basename "$0") [profile] [options]...\nAvailable profiles:\n\t$(for file in "$OISETUP_PROFILES_PATH"/*; do test -L "$file" || basename "$(echo "$file")"; done | sort | xargs)\nProfiles are located in:\n\t$OISETUP_PROFILES_PATH\nOptions:\n\t-d --defragment\tDefragment the disk (so it can later be compacted and compressed for distribution)\n\t-r --refresh\tOnly refresh the profile, keep persistent data\n\t-i --install\tUpdate and install from repo\n\t-c --config-os\tSets up the contest environment\n-F --skip-os-checks\tDo not check if the OS matches\n\t-h --help\tDisplay this help message"
         exit ${param_error:+1}
 fi
+
+# Update and install from the repo
+is_enabled "$param_install" && ! is_enabled "$param_skipinstall" && install_from_repo && exec "$0" "$@" --skip-install
 
 test -z "$param_profile" && param_refresh="true" param_profile="$DEFAULT_OISETUP_PROFILE"
 profile_path="$OISETUP_PROFILES_PATH/$param_profile"
@@ -729,13 +876,8 @@ test -n "$DNS_LOCKDOWN_ALLOWLIST" -o -n "$DNS_LOCKDOWN_WHITELIST" && for domain 
 # We need to disable the lockdown as some settings might require internet access
 dns-lockdown stop 2>/dev/null
 
-# Update from the repo
-is_enabled "$param_gitpull" && update_from_repo "$@"
-
-! test -d "$REPO_PATH/vm-contestant" && error "$REPO_NAME repository not found in $REPO_PATH. Call with --gitpull to download it."
-
-# Install proctoring system
-install_proctor
+# Install required tools
+install_requirements
 
 # Recommend installing VM tools
 detect_vm_tools
